FROM ocaml/opam:debian-11 as opam
FROM debian:bullseye as build
RUN apt-get update && env DEBIAN_FRONTEND=noninteractive apt-get -qq install -y ruby ruby-dev rubygems build-essential curl git bzip2
RUN mkdir -p /tmp/installdir/usr/bin /tmp/installdir/usr/lib
RUN cd /root && curl -OL https://github.com/ocaml/ocaml/archive/refs/tags/4.14.0.tar.gz && tar -xf 4.14.0.tar.gz && cd ocaml-4.14.0 && ./configure --prefix=/usr && make -j world.opt 2>&1 >/dev/null && make install DESTDIR=/tmp/installdir && make install && cd / && rm -f /root/4.14.0.tar.gz && rm -rf /root/ocaml-4.14.0
COPY --from=opam /usr/bin/opam-2.1 /usr/bin/opam
COPY --from=opam /usr/bin/opam-2.1 /tmp/installdir/usr/bin/opam
