name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: 0 1 * * MON

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  debs:
    runs-on: self-hosted
    needs: [docker]
    steps:
      -
        name: Build and push Debian packages
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.deb
          build-args: OCAML_VERSION=4.14.0
          push: true
          pull: true
          no-cache: true
          tags: ghcr.io/avsm/ocaml-devcontainer:4.14-debs
          platforms: linux/arm64,linux/amd64
  repo:
    runs-on: self-hosted
    needs: [debs]
    steps:
      -
        name: Build and push Debian repo
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.debrepo
          push: true
          pull: true
          no-cache: true
          tags: ghcr.io/avsm/ocaml-devcontainer:debrepo
          platforms: linux/arm64,linux/amd64 
