name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: 0 1 * * MON

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  repo:
    runs-on: self-hosted
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build and push Debian repo
        uses: docker/bake-action@master
        with:
          push: true
      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: ghcr.io/avsm/ocaml-devcontainer:debs
          path: /srv
      - name: Upload debs to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.extract.outputs.destination }}/*.deb
          tag: debs
        overwrite: true
        file_glob: true
