name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: 0 1 * * MON

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Debian packages
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.deb
          push: true
          pull: true
          no-cache: true
          tags: avsm/ocaml-devcontainer:4.14-debs
          platforms: linux/arm64,linux/amd64 
      -
        name: Build and push Debian repo
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.debrepo
          push: true
          pull: true
          no-cache: true
          tags: avsm/ocaml-devcontainer:debrepo
          platforms: linux/arm64,linux/amd64 
